version: "3.8"
services:
            
    mysql:
        hostname: mysql
        image: mysql
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=got_db
            - MYSQL_PASSWORD=root
        ports:
            - "3306:3306"
            - "33060:33060"
        networks:
            - connection1

    got_project:
        hostname: got_project
        build: .
        image: gotidp
        container_name: got_project
        environment:
            - GoT_URL=https://game-of-thrones1.p.rapidapi.com/
            - X-RapidAPI-Key=61839e0a48mshb77ebc6d900e5c5p14782ejsn44f6de44822c
            - X-RapidAPI-Host=game-of-thrones1.p.rapidapi.com
            - databaseUrl=mysql
            - SPRING_PROFILES_ACTIVE=prod
        ports:
            - "8080:8080"
        networks:
            - connection1
        depends_on:
            - mysql
            

networks:
    connection1:
        driver: bridge